### ISSUE TITLE
raw_sim.fif для systemtest_beam.by

### ISSUE THREAD

**Issue by logogriph2** [dmalt/cognigraph#10]
Откуда можно скачать файл raw_sim.fif, нужный для systemtest_beam.зy?

**Comment by dmalt** [comment]
Выложил на gdrive: https://drive.google.com/open?id=1nICqhz7nicyC8aSjF1DdIWUHunIjkZm0

**Comment by dmalt** [comment]
Вот ссылка на папку с остальными тестовыми данными: https://drive.google.com/open?id=1W0fGpVeoj_r7EogGaNEptQQ8kbns54_S

**Comment by logogriph2** [comment]
после добавления файлов несколько ошибок исчезли. Сейчас программа вылетает с логом:
![beam_error](https://user-images.githubusercontent.com/24354709/45866673-365cfb80-bd8a-11e8-852a-27e444e079e9.jpg)

**Comment by dmalt** [comment]
Да, там действительно ошибка в расчете сглаживающей сатрицы, связанная с переходом на новую визуализацию.  Расчет сглаживающей матрицы происходит только если нет сохраненной матрицы.  Пока исправления не готовы, вы можете поместить вот эти файлы (https://drive.google.com/file/d/1YACxvGCtxRUCi-q-bF9ny2aKkfx0844O/view?usp=sharing
https://drive.google.com/file/d/15qo8wXH4mVfJrZ7cuACEGT0H-Ja3sX-F/view?usp=sharing
https://drive.google.com/file/d/1VGSoWD2kRitVT0MBwKfSeJWSfprCE3-c/view?usp=sharing) 
в папку cognigraph/tests/data --- Это исправит проблему.

**Comment by dmalt** [comment]
Поправил расчет сглаживающей матрицы.
