### ISSUE TITLE
загрузка fif-файла

### ISSUE THREAD

**Issue by logogriph2** [dmalt/cognigraph#11]
В меню загрузки данных нет формата fif
![fif_error](https://user-images.githubusercontent.com/24354709/45878913-71bbf200-bdab-11e8-9ce0-7c43a802b9d9.jpg)

**Comment by dmalt** [comment]
Какой скрипт вы запускали?

**Comment by logogriph2** [comment]
systemtest_mce.py

**Comment by dmalt** [comment]
Можете втавить сюда исходный код systemtest_mce.py?

**Comment by logogriph2** [comment]
[systemtest_mce.txt](https://github.com/dmalt/cognigraph/files/2405572/systemtest_mce.txt)

**Comment by dmalt** [comment]
Да, это старая версия. Сравните с тем, что в мастере: https://github.com/dmalt/cognigraph/blob/master/tests/systemtest_mce.py

**Comment by logogriph2** [comment]
скачал заново. такой лог при запуске является нормой?
[log_mce.txt](https://github.com/dmalt/cognigraph/files/2405632/log_mce.txt)

**Comment by dmalt** [comment]
Это та же ошибка, что и здесь https://github.com/dmalt/cognigraph/issues/10.
Нужно поместить эти файлы в tests/data
(https://drive.google.com/file/d/1YACxvGCtxRUCi-q-bF9ny2aKkfx0844O/view?usp=sharing
https://drive.google.com/file/d/15qo8wXH4mVfJrZ7cuACEGT0H-Ja3sX-F/view?usp=sharing
https://drive.google.com/file/d/1VGSoWD2kRitVT0MBwKfSeJWSfprCE3-c/view?usp=sharing)

**Comment by logogriph2** [comment]
Да, после их загрузки заработало. Спасибо!
