### ISSUE TITLE
systemtest_mce error

### ISSUE THREAD

**Issue by logogriph2** [dmalt/cognigraph#12]
При попытке запустить тест для данных DF_2018-03-02_11-34-38-fwd.fif возникает ошибка.
Нужную smoothing matrix скачал.

[mce_error_log.txt](https://github.com/dmalt/cognigraph/files/2405839/mce_error_log.txt)

**Comment by logogriph2** [comment]
ясно. все файлы с fwd - прямая модель?

**Comment by dmalt** [comment]
Да. Это соглашение mne-python
