### ISSUE TITLE
генератор pytorch-тензоров с источниками

### ISSUE THREAD

**Issue by logogriph2** [dmalt/cognigraph#14]
Скажите, а в каком из модулей реализовано создание генератора pytroch тензоров с источниками для файлов формата edf/edf+, fif, eeg ?

**Comment by dmalt** [comment]
Вот здесь в самом конце https://github.com/dmalt/cognigraph/blob/master/cognigraph/nodes/outputs.py.

**Comment by logogriph2** [comment]
ок, принято
