### ISSUE TITLE
юнит-тесты

### ISSUE THREAD

**Issue by logogriph2** [dmalt/cognigraph#15]
юинт-тесты модулей из узлов находятся только в папке tests? можете ли вы описать процесс тестирования? 
(я обычно для каждой функции пишу скрипт, который подает на нее заранее подготовленные данные и сравнивает выход функции с тем, который должен получиться на этих данных)

**Comment by dmalt** [comment]
Да, все тесты находятся в папке tests. Там есть старые скрипты, которые нужно удалить, забрав из них все нужное и полезное. Из актуальных там три файла с юнит-тестами (test_*.py) и два системных теста, они же скриты, демонстрирующие работу программы (systemtest_*.py). Юнит-тесты реализованы на основе фреймворка pytest. Для их запуска нужно пойти в корневую папку когниграфа и запустить из консоли (из системной, не из питоновской) команду `pytest`. Юнит-тесты  тестируют отдельные функции узлов решения обратной задачи. Часть тестов проверяет, что функция просто запускается, какие-то смотрят, что определенные аттрибуты выставлены в правильные значения. Я согласен, что нужно еще сделать проверку функции update на тестовых данных,  но я пока не придумал, как их правильно хранить, потому что на гитхабе держать данные плохо, а хочется, чтобы тесты работали автоматически без необходимости что-то скачивать. Кроме того, я хочу настроить Travis, который автоматически будет запускать эти тесты проверяя каждый новый коммит. Для оценки адекватности работы модулей ОЗ я предполагал использование системных тестов.

**Comment by dmalt** [comment]
Прошу прощения, сейчас юнит-тесты все-таки используют тестовые данные. От этого либо нужно уйти, либо цеплять их из облака автоматически. С автоматической проверкой вывода решения ОЗ другая проблема -- не очень понятно, как выяснить, что решение правильное, не глядя на картинку,  потому что численно решение может несколько отличаться от того, что я получаю например при помощи mne-python. Особенно это касается бимформеров и MCE.  В первом случае  для ускорения оптимальная ориентация ищется приближенным итерационным методом, а MCE и вовсе не с чем сравнивать, т.к. этот алгоритм нигде не очень-то используется.

**Comment by logogriph2** [comment]
Вы уверены, что из системной? или дело в ОС?
![pytest_error](https://user-images.githubusercontent.com/24354709/46212345-6eda7780-c33e-11e8-9440-1ae58c76d039.jpg)

**Comment by logogriph2** [comment]
разобрался, запустил
