### ISSUE TITLE
Smoothing matix

### ISSUE THREAD

**Issue by logogriph2** [dmalt/cognigraph#19]
Должны ли smoothing matrix вычисляться программой или их нужно подгружать?

Reading forward solution from C:\DL_projects\cognigraph-master/tests/data/dmalt_custom_mr-fwd.fif...
    Reading a source space...
    [done]
    Reading a source space...
    [done]
    2 source spaces read
    Desired named matrix (kind = 3523) not available
    Read EEG forward solution (4220 sources, 121 channels, free orientations)
    Source spaces transformed to the forward solution coordinate frame
    No patch info available. The standard source space normals will be employed in the rotation to the local surface coordinates....
    Converting to surface-based source orientations...
    [done]
MCE: COMPUTING SVD OF THE FORWARD OPERATOR
Initializing the ThreeDeeBrain node
Calculating smoothing matrix. This might take a while the first time.
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
C:\DL_projects\cognigraph-master\cognigraph\nodes\outputs.py in _get_smoothing_matrix(self, mne_forward_model_file_path)
    395         try:
--> 396             return sparse.load_npz(smoothing_matrix_file_path)
    397         except FileNotFoundError:

~\Anaconda3\lib\site-packages\scipy\sparse\_matrix_io.py in load_npz(file)
    129
--> 130     with np.load(file, **PICKLE_KWARGS) as loaded:
    131         try:

~\Anaconda3\lib\site-packages\numpy\lib\npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    371     if isinstance(file, basestring):
--> 372         fid = open(file, "rb")
    373         own_fid = True

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\DL_projects\\cognigraph-master/tests/data/dmalt_custom_mr-fwd-smoothing-matrix.npz'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
C:\DL_projects\cognigraph-master\tests\systemtest_mce.py in <module>()
     87 # three_dee_brain_controls.limits_mode_combo.setValue('Local')
     88
---> 89 window.initialize()
     90
     91 start_s, stop_s = 80, 100

C:\DL_projects\cognigraph-master\cognigraph\gui\window.py in initialize(self)
     51
     52     def initialize(self):
---> 53         self._pipeline.initialize_all_nodes()
     54         for node_widget in self._node_widgets:
     55             node_widget.setMinimumWidth(600)

C:\DL_projects\cognigraph-master\cognigraph\pipeline.py in initialize_all_nodes(self)
     92         t1 = time.time()
     93         for node in self.all_nodes:
---> 94             node.initialize()
     95         t2 = time.time()
     96         self.logger.info(

C:\DL_projects\cognigraph-master\cognigraph\nodes\node.py in initialize(self)
    121         with self.not_triggering_reset():
    122             print('Initializing the {} node'.format(class_name_of(self)))
--> 123             self._initialize()
    124             t2 = time.time()
    125             self.logger.info('Finish initialization in {:.1f} ms'.format((t2 - t1) * 1000))

C:\DL_projects\cognigraph-master\cognigraph\nodes\outputs.py in _initialize(self)
    130         mne_forward_model_file_path = self.traverse_back_and_find(
    131             'mne_forward_model_file_path')
--> 132         self._brain_painter.initialize(mne_forward_model_file_path)
    133
    134         frequency = self.traverse_back_and_find('mne_info')['sfreq']

C:\DL_projects\cognigraph-master\cognigraph\nodes\outputs.py in initialize(self, mne_forward_model_file_path)
    232             self.widget = self._create_widget()
    233         self.smoothing_matrix = self._get_smoothing_matrix(
--> 234             mne_forward_model_file_path)
    235         # else:  # Do not recreate the widget, just clear it
    236         #     for item in self.widget.items:

C:\DL_projects\cognigraph-master\cognigraph\nodes\outputs.py in _get_smoothing_matrix(self, mne_forward_model_file_path)
    400             sources_idx, _ = self._get_mesh_data_from_forward_solution(
    401                 mne_forward_model_file_path)
--> 402             adj_mat = mesh_edges(self.mesh_data.faces())
    403             smoothing_matrix = smoothing_matrix(sources_idx, adj_mat)
    404             sparse.save_npz(smoothing_matrix_file_path, smoothing_matrix)

AttributeError: 'Brain' object has no attribute 'faces'

**Comment by dmalt** [comment]
Подождите пожалуйста, я закоммитил не все изменения пока. В течение получаса выложу все.
Конкретно эта ошибка уже исправлена. Скачайте свежую версию мастера.

**Comment by dmalt** [comment]
Я все добавил в мастер.

**Comment by logogriph2** [comment]
спасибо, теперьработает
