### ISSUE TITLE
Подключение nfb

### ISSUE THREAD

**Issue by logogriph2** [dmalt/cognigraph#8]
После копирования и распаковки pynfb из https://github.com/nikolaims/nfb/tree/e7c4059e2cce0ba5f8cd1cb68c332d3e566c68a6 в vendor возникает ошибка поиска модуля. при запуске всех тестов ipython.
При запуске тестов в среде pyCharm ошибки с модулем не возникает.
![pynfb](https://user-images.githubusercontent.com/24354709/45819041-02cb9400-bcec-11e8-8ca4-2d2cdc443c8c.jpg)

**Comment by dmalt** [comment]
Тест необходимо запускать из кореневой папки когниграфа, например ```python tests/systemtest_beam.py```. Вы так делаете?

**Comment by logogriph2** [comment]
да.
последовательность команд:
![systemtest_mce_error](https://user-images.githubusercontent.com/24354709/45865982-f3018d80-bd87-11e8-85fe-547f39c5621d.png)

**Comment by dmalt** [comment]
Ошибка воспроизвелась. Сейчас разберусь и поправлю

**Comment by logogriph2** [comment]
спасибо! теперь работает!
