### ISSUE TITLE
Запуск systemtest_mce

### ISSUE THREAD

**Issue by logogriph2** [dmalt/cognigraph#9]
При запуске systemtest_mce.py программа аварийно завершается.

Вывод консоли:
C:\DL_projects\cognigraph-master\tests/data/

Process finished with exit code -1073740791 (0xC0000409)

**Comment by dmalt** [comment]
Выложите пожалуйста команду, которой вы запускаете скрипт.

**Comment by dmalt** [comment]
Закрываю?
